name: Branch Cleanup
on:
  push:
    branches: [clean]
  schedule:
    - cron: "0 0 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean up unused Branches
        run: |
          git fetch --prune 
          git branch -r --merged origin/main | grep -v "origin/main" || echo "No branches to cleanup"