name: Slack Notification

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deployment Successful!"

      - name: Send Notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: '#general'  # اتأكد إن فيه قناة في سلاك اسمها general
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_MESSAGE: 'Build and deployment successful for Abo 3mera Project! 🚀'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}